name: "Docker Image"

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        with:
          platforms: 'arm64,amd64'

      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      -
        name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"

      -
        id: docker_build
        name: "Build and push Docker images"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "robtarr/dns-updater:latest"
          platforms: linux/amd64,linux/arm64

      -
        name: "Image digest"
        run: "echo ${{ steps.docker_build.outputs.digest }}"
